### ISSUE TITLE
Requests and questions:

### ISSUE THREAD

**Issue by denizzzka** [denizzzka/vibe.d.db.postgresql#1]
Please feel free to request something!

**Comment by stonemaster** [comment]
As far as I can see this library is based on libpq, right? That actually means that it doesn't natively support Vibe.d sockets and might block a Vibe worker thread/fiber if the connection to the Postgres server goes down. Or have I missed something? I think this is a very important point ..

**Comment by denizzzka** [comment]
> As far as I can see this library is based on libpq, right?

Yes

> That actually means that it doesn't natively support Vibe.d sockets and might block a Vibe worker thread/fiber if the connection to the Postgres server goes down.

Nope

> Or have I missed something? I think this is a very important point ..

Sure!

libpq can work with blocking and unblocking sockets and have non-blocking versions of all its blocking functions.
Thus, with libpq you have 3 ways for server interaction:
* blocking (such as PQexec)
* blocking socket with non-blocking functions (such as PQsendQuery) - preferred for vibe.d, as I understand
* non-blocking socket with non-blocking functions (PQsendQuery + non-blocking socket)

Also, libpq allows to obtain connection socket for watching about its activity. All this stuff allows to set up cooperative multi-tasking support.

(Currently vibe.d.db.postgresql contains small bug with async connections support which I brought a couple of days ago. It will be fixed in short time.)

**Comment by stonemaster** [comment]
Thank you for the very detailed answer! This clarifies a lot. I wasn't aware of those details in libpq.

**Comment by ddcovery** [comment]
Some additional examples  (transaction, insert returning, parameters, PQcmdTuples) showing basic operative would be apreciated.

**Comment by denizzzka** [comment]
vibe.d.db.postgresql uses https://github.com/denizzzka/dpq2 for DB backend, so, examples for dpq2 should be suitable.

(But PQcmdTuples currently isn't implemented in dpq2.)

**Comment by ddcovery** [comment]
Thank you Denis

**Comment by Boris-Barboris** [comment]
Hi, it's me again.

What's the story behind connection pool reimplementation, why was it needed?
I had a great time time with stock vibe-core connection pool, It works ok.
Also, why not block here: https://github.com/denizzzka/vibe.d.db.postgresql/blob/master/source/vibe/db/postgresql/package.d#L53
It's the perfect place to block actually.

**Comment by Boris-Barboris** [comment]
Is it because you want to share conection pool between OS threads?
I think it's the wrong way, giving each worker thread it's own pool will remove all complex interlocking.

**Comment by denizzzka** [comment]
> Hi, it's me again.

Hi!

> What's the story behind connection pool reimplementation, why was it needed?

I do not remember exactly. At least, at start of this package development vibe.d pool was glitchy. And maybe lack of some methods needed by this package.

> I had a great time time with stock vibe-core connection pool, It works ok.

PR which exchanges my own pool to vibe.d are welcome!

> Also, why not block here: https://github.com/denizzzka/vibe.d.db.postgresql/blob/master/source/vibe/db/postgresql/package.d#L53
> It's the perfect place to block actually.

Block what?

**Comment by Boris-Barboris** [comment]
>Block what?
the fiber that tries to lock the connection from the pool. But I kinda answered my own question, when I saw shared.

>PR which exchanges my own pool to vibe.d are welcome!
Ok, brb, will slap on some TLPostgresClient (thread-local)

**Comment by denizzzka** [comment]
> Is it because you want to share conection pool between OS threads?

Maybe. But currently it isn't usable because for Linux libpq's connections sharing isn't thread-safe.

> I think it's the wrong way, giving each worker thread it's own pool will remove all complex interlocking.

If will be created some number of workers threads it isn't need to create pools at all.

Vibe.d uses pools because it handles thousands of connections. At first I thinked that vibe.d.db.postgresql also need to support many connections. But my current installations use only few connections usually.

**Comment by Boris-Barboris** [comment]
> But currently it isn't usable because for Linux libpq's connections sharing isn't thread-safe.

Even more reasons to get rid of it.

> Vibe.d uses pools because it handles thousands of connections. At first I thinked that vibe.d.db.postgresql also need to support many connections. But my current installations use only few connections usually.

Not as many, yes (mainly because PSQL itself cannot handle many), around 2-4 per thread is good in my experience, but pool is needed.

**Comment by denizzzka** [comment]
> Even more reasons to get rid of it.

There are several serious reason not to get rid of it: the fact that this library is a part of the server code. Thus, if the protocol changes (silently - why not?) it will not be a problem, no data loss or something like that. (Wе do not want to store "almost correct" values in our DB)

> mainly because PSQL itself cannot handle many

??

**Comment by Boris-Barboris** [comment]
>??

I've read several posts stating the practical limit of a couple of hundred, with some guides to puhs it to 1000. Spawning OS process for each one is one of the reasons. By no means I can call it "many".

**Comment by denizzzka** [comment]
Are you sure that libpq spawns a process for each connection?

**Comment by Boris-Barboris** [comment]
Postgres server itself does.

**Comment by denizzzka** [comment]
> Postgres server itself does.

Yes, but for client I am isn't sure. The link above is evasive.

**Comment by Boris-Barboris** [comment]
yo, can you create a branch for me?

**Comment by denizzzka** [comment]
> so there's no need to agressively pool tens or hundreds of connections on the front

But we can connect to many diffrent servers with same data! (My own software does it right now)

> yo, can you create a branch for me?

Just fork, create branch and make PR

**Comment by denizzzka** [comment]
>> Even more reasons to get rid of it.
> There are several serious reason not to get rid of it: the fact that this library is a part of the server code. Thus, if the protocol changes (silently - why not?) it will not be a problem, no data loss or something like that. (Wе do not want to store "almost correct" values in our DB)

Remembered another reason: libpq includes implementation of various types of connections with various types of authentifications. For example, I am sure what Kerberos isn't available in another Postgres clients, but this is critical for desktop applications.

**Comment by Boris-Barboris** [comment]
I meant: to get rid of custom connection pool.

**Comment by denizzzka** [comment]
closing for code.dlang.org scoring increase :-)
