### ISSUE TITLE
Looking at starting a postgres/vibed project

### ISSUE THREAD

**Issue by schveiguy** [denizzzka/vibe.d.db.postgresql#23]
I add this library as a dependency in dub, but it grabs version 0.2.24 from over a year ago. Is that right? I suppose it's because all the newer versions have 'alpha' and 'beta' in the name. What should I use?

**Comment by schveiguy** [comment]
So to clarify, I'm creating a new project, dub asks if I want to do any dependencies, I type in `vibe-d-postgresql`, and it grabs 0.2.24. And BTW doesn't build with the latest compiler.

Since then I have manually selected the 2.0.0-alpha.3 version. But the issue I'm bringing up is, there are no "official" releases for dub to grab since that version, so that's what it uses. You may want to add versions without beta or alpha in the tags on a 1.0.0 or 0.3 version so people get the latest workable code.

How stable is the 2.0.0-alpha.3 version? I'm new to postgres, so this is a learning experience for me.

**Comment by denizzzka** [comment]
> dub asks if I want to do any dependencies, I type in vibe-d-postgresql, and it grabs 0.2.24

Never used this functionality of DUB.
Does DUB use latest version "without letters" (alpha, etc) in this case or so?

> How stable is the 2.0.0-alpha.3 version?

More stable whan 0.2.24

I planning to release new stable after merging or declination of #22

**Comment by schveiguy** [comment]
> Never used this functionality of DUB.
> Does DUB use latest version "without letters" (alpha, etc) in this case or so?

I'm not sure. My guess is that it uses only semver compatible versions. But that's a guess based on the given behavior, not based on the actual implementation. Someone who maintains dub would know more.

**Comment by denizzzka** [comment]
can we close this?

**Comment by denizzzka** [comment]
I just released new version without suffix

maybe it is need to report DUB issue?

**Comment by schveiguy** [comment]
> maybe it is need to report DUB issue?

No, this is as designed. Essentially, if you want to create a project using dub, you don't want to depend on (probably broken) alpha or beta versions (pre-release versions). It's just that this project hadn't had a non-alpha release for a long time. Thanks for the fix!

**Comment by denizzzka** [comment]
>  Essentially, if you want to create a project using dub, you don't want to depend on (probably broken) alpha or beta versions (pre-release versions)

hmmm. But I definitely want to use alpha version by adding it to dub config dependencies

**Comment by denizzzka** [comment]
>  people don't necessarily want to use an alpha version in production code

But often they just have no choice. If someone selects 2.x.x version and here is only -alpha is available this alpha should be choised, not 1.x.x.

**Comment by schveiguy** [comment]
The use case is when someone lets dub decide the version. I didn't say "I want the latest 2.x.x version".

In most software projects, you have a stable release and an alpha release. For a project where I'm not needing to be on the bleeding edge, I was unsure to get the alpha release, which is why I posted this issue -- the stable release wasn't working.

I'm pretty sure that dub will not pick a prerelease version unless you specifically ask it to. This is because in semver projects, a prerelease does not guarantee everything works or even builds. So even if I said "~>2.0.0", it would not have given me the alpha. Note that the alpha is a *prior release* to 2.0.0, so logically it would be excluded anyway.

**Comment by denizzzka** [comment]
Ok, maybe it is need to patch code.dlang.org to avoid announcing dependency lines with versions such as discussed here?

**Comment by schveiguy** [comment]
> So, DUB should report "no suitable version found" in this case?

I think it would have, before the recent release of 2.0.0. I think in order to select the alpha version, you had to specifically ask for that version.

> Or maybe it is need to patch code.dlang.org to avoid announcing dependency lines with versions such as discussed here?

I think maybe there is a misunderstanding, dub code choices are correct, the issue was simply with a stale stable version of this repository. pre-release versions must be specifically selected. Those rules aren't going to change.

Going forward, what I would recommend is if something is broken/doesn't work, add a new revision release to fix it WITHOUT going through alpha/beta stage, or at least if you do alpha/beta make sure it's for a short period of time. This way, people who are not interested in development versions of your library can select a suitable stable release that works with the rest of the D ecosystem.

**Comment by denizzzka** [comment]
> Since then I have manually selected the 2.0.0-alpha.3 version.

with `~>` prefix?

**Comment by schveiguy** [comment]
> with `~>` prefix?

Probably, but I don't know if it matters. I will be changing to 2.0.0 version.
