### ISSUE TITLE
Keep lockConnection

### ISSUE THREAD

**Issue by schveiguy** [denizzzka/vibe.d.db.postgresql#34]
The unreleased version 3.0.0 deprecates lockConnection in favor of pickConnection.

I disagree with the solution, even though I've seen such solutions on other projects in other languages (mostly to deal with mutex locking).

1. The goal of pickConnection is to handle errors automatically by calling .reset when an exception occurs. However, it's simple to catch an exception and do something different. So this still does not solve the problem.
2. The change is not backwards compatible with existing usage. One cannot simply replace calls to lockConnection with pickConnection. One has to redesign their usage calls.
3. If you need 2+ connections for any reason, then you will need to nest calls to pickConnection, which is starting to look like node.js. Not only that, but an error in one connection will possibly cause an unnecessary reset in the other connection.

I would recommend instead storing a flag with the connection for when it needs a reset, and calling that before the next usage (I'm assuming this is why you need to call it).

mysql-native does it by closing the connection automatically on a failure (see [here](https://github.com/mysql-d/mysql-native/blob/8f9cb4cd9904ade43af006f96e5e03eebe7a7c19/source/mysql/protocol/comms.d#L760)). The next time something is tried, it reconnects.

Alternatively, you can simply not deprecate lockConnection and leave the warning in the documentation for those who do not wish to use the delegate-like calls.

**Comment by schveiguy** [comment]
ping @denizzzka see #36 

I'm not sure what you mean by "explanation code comments", I thought the current comments were reasonable.

**Comment by denizzzka** [comment]
> I'm not sure what you mean by "explanation code comments", I thought the current comments were reasonable.

I Agree

**Comment by denizzzka** [comment]
fixed in #36 
thanks!
