### ISSUE TITLE
No longer builds due to import failure

### ISSUE THREAD

**Issue by atilaneves** [denizzzka/vibe.d.db.postgresql#5]
`.dub/packages/vibe-d-postgresql-0.2.19/vibe-d-postgresql/source/vibe/db/postgresql/package.d(4,15): Error: module dpq2 import 'Dpq2Exception' not found`

**Comment by denizzzka** [comment]
Thanks!

**Comment by atilaneves** [comment]
No problem. Could you tag a new version please?

**Comment by denizzzka** [comment]
Sure!
